# https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "9"
cache: yarn
# https://github.com/greenkeeperio/greenkeeper-lockfile#yarn
# depends on $GH_TOKEN
before_install: yarn global add greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn
  - yarn lerna run clean
  - yarn lerna bootstrap
  - (cd packages/angular-skyhook && yarn run build)
  - (cd packages/angular-skyhook-card-list && yarn run build)
  - (cd packages/angular-skyhook-multi-backend && yarn run build)
  - (cd packages/examples && yarn test:headless)
  - bash ./build-docs.sh --travis
deploy:
  provider:     pages
  skip_cleanup: true
  local_dir:    out-docs
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
